### ISSUE TITLE
Can't make search request: 402 Payment Required

### ISSUE THREAD

**Issue by noduck** [jlouder/garmin-connect-perl#4]
When using the activities() method, there is the following error: Can't make search request: 402 Payment Required. This looks like it is the result of a change in the Garmin Connect API.

**Comment by jlouder** [comment]
I'm seeing the same thing beginning yesterday. I'll see if I can figure out what changed in their API.

**Comment by noduck** [comment]
Thanks for the quick fix, works for me!
